// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, customerID int64) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	DecrementProductStock(ctx context.Context, arg DecrementProductStockParams) (int64, error)
	FindProductByID(ctx context.Context, id int64) (Product, error)
	GetOrderByID(ctx context.Context, id int64) (Order, error)
	ListOrderItemsByOrderID(ctx context.Context, orderID int64) ([]ListOrderItemsByOrderIDRow, error)
	ListProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
