FROM golang:1.26-alpine

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

WORKDIR /app

COPY internal/adapters/postgresql/migrations ./migrations

CMD ["goose", "-dir", "./migrations", "postgres", "host=db user=postgres password=postgres dbname=ecom sslmode=disable", "up"]